- .gitignore
- ormconfig.js
- package-lock.json
- package.json
- src/app.module.ts
typeorm을 사용하여 로컬 mysql db와 nestjs 서버와 연결하였습니다.
로컬환경에서 .env 파일 생성이 필요합니다.
> feat(typeorm): mysql initial setting

- .prettierrc
coding style 통일을 위해 prettier 세팅하였습니다.
> style: prettier setting

- .github/workflows/build-and-test.yml
- package-lock.json
- package.json
- src/app.controller.spec.ts
coverage 측정에 사용하던 coverage-report-action을 codecov로 변환하였습니다.
> ci(codecov): change coverage-report-action to codecov-action

- package-lock.json
- package.json
- src/app.module.ts
- src/running-route/entities/route-tag.entities.ts
- src/running-route/entities/running-route.entity.ts
- src/user/entities/bookmark.entity.ts
- src/user/entities/like.entity.ts
- src/user/entities/user-tag.entity.ts
- src/user/entities/user.entity.ts
TypeORM을 사용하여 User, RunningRoute, Bookmark, Like, UserTag, RouteTag 테이블을 정의하였습니다.
> feat(db): create database tables

- src/user/entities/user.entity.ts
와이어프레임에 따라 필요한 attribute를 user 테이블에 추가하였습니다.
> feat(db): add attributes to USER table

- package-lock.json
- src/app.module.ts
- src/auth/auth.controller.ts
- src/auth/auth.module.ts
- src/auth/auth.service.ts
- src/auth/guards/jwt-auth.guard.ts
- src/auth/guards/loacl-auth.guard.ts
- src/auth/strategies/jwt.strategy.ts
- src/auth/strategies/local.strategy.ts
- src/user/dto/create-user.dto.ts
- src/user/dto/login-user.dto.ts
로그인 함수 구현하였습니다.
로그아웃은 클라이언트 상에서 저장하고 있던 토큰을 지우면 됩니다.
로그인이 정상적으로 수행되었을 때
잘못된 비밀번호를 사용하였을 때
존재하지 않는 아이디로 로그인을 시도하였을 때
정상 토큰을 가지고 프로필을 확인한 경우
잘못된 토큰을 가지고 프로필을 확인한 경우
> feat(auth): create login api using JWT

- src/running-route/dto/create-running-route.dto.ts
- src/running-route/entities/running-route.entity.ts
- src/running-route/running-route.service.ts
runningRoute 테이블에 routeName 칼럼을 추가하였습니다.
그에 따라 create, getById API에 routeName 부분을 추가하였습니다.
create
getById
> feat(db): add routeName attribute

- src/app.module.ts
- src/user/dto/create-user.dto.ts
- src/user/entities/user-recommended-tag.entity.ts
- src/user/entities/user-secure-tag.entity.ts
- src/user/entities/user.entity.ts
- src/user/user.controller.spec.ts
- src/user/user.module.ts
- src/user/user.service.spec.ts
- src/user/user.service.ts
기존의 user Tag를 추천과 안전 태그로 분리하였습니다.
또한 회원가입시 해당 정보를 입력하도록 수정하였습니다.
```json
{ 
"name" : "test_name", 
"nickname" : "test_nickname", 
"userId" : "test_id", 
"password" : "test1234", 
"birthDate" : "2022-01-01", 
"gender" : "F", 
"address" : "test address",
"recommendedTags" : [1,2,4],
"secureTags" : [1,3,5]
}
```
create user
```json
{ 
"recommendedTags" : [10],
"secureTags" : [10]
}
```
update user
delete user
> Feat/#27 : userRecommendedTag, userSecureTag (db,api)

- src/user/dto/create-user.dto.ts
- src/user/entities/user.entity.ts
- src/user/user.service.spec.ts
~~이메일 인증 구현~~
우선 순위 상 추후 구현으로 일정 변경하겠습니다
> feat(db): add email attributes to user

- src/running-route/running-route.controller.ts
- src/running-route/running-route.service.ts
running-route create, update, delete API에 user 정보를 추가하였습니다.
사용자가 등록한 전체 경로 및 따라가기 경로 API를 추가하였습니다.
get AllMainRoute
get AllSubRoute
> Feat/#40 : connect route API with user & add getAll API

- src/auth/auth.service.ts
카카오 로그인 중 신규 회원 정보를 저장하는 api에 문제가 있어 수정하였습니다.
> fix(kakao): fix kakao sign in api

- src/running-route/entities/running-route.entity.ts
- src/running-route/running-route.controller.ts
- src/running-route/running-route.service.ts
경로 이름 중복이 있는지 확인하는 api입니다.
중복이 있을 경우 해당 길 이름을 가진 경로가 몇개나 있는지에 대한 count 값도 함께 전달합니다.
DB에 저장된 경로 이름
중복 이름이 있는 경우
중복 이름이 없는 경우
> feat(route): add checkRouteName API

- src/auth/auth.module.ts
- src/user/dto/create-bookmark.dto.ts
- src/user/dto/delete-bookmark.dto.ts
- src/user/user.controller.ts
- src/user/user.module.ts
- src/user/user.service.ts
- Bookmark
- create (경로 저장)
- delete (저장 경로 삭제)
- getAll ( 저장한 경로 목록 불러오기 )
> Feat/#45 : Create Bookmark API

- src/running-route/running-route.controller.ts
- src/running-route/running-route.service.ts
메인 홈 화면에 있는 사용자 현재 위치 기반 추천 경로 api 입니다.
위치 기반 검색과 반경 계산법이 동일하여 해당 동작을 calculateDistance 함수로 묶어 사용하였습니다.
> feat(route): add getRecommendedRoute API

- src/user/user.controller.spec.ts
- src/user/user.controller.ts
- src/user/user.module.ts
- src/user/user.service.spec.ts
- src/user/user.service.ts
> test(fix): fix test code error

- src/user/user.controller.ts
- src/user/user.service.ts
- increaseUseRecommended (사용자가 추천경로를 사용하였을 때 호출)
- getUseRecommended (사용자가 몇번 추천경로를 사용하였는지 가져올 때 호출)
> feat(user): create numberOfUse related api

- src/running-route/running-route.controller.spec.ts
- src/running-route/running-route.service.spec.ts
- src/running-route/running-route.service.ts
create와 update api에서 세부적인 트랜잭션 처리를 위해 queryRunner를 이용한 코드로 수정하였습니다.
두번째 경로를 생성할 때 임의로 추천 태그 저장 쿼리에 오류를 발생하였고 그 결과 롤백 되어 다음 경로는 3번으로 저장되는 것을 확인하였습니다.
> fix(route): fix transactional action of route API

- src/running-route/running-route.controller.ts
- src/running-route/running-route.service.ts
프론트 연결을 위해 create, update, delete api에 token을 임시로 주석처리했습니다.
> fix(route): delete token

- src/running-route/dto/create-running-route.dto.ts
- src/running-route/running-route.service.ts
<이미지 파일 업로드>
프론트에서 보내주는 base64 스트링을 디코딩하여 s3에 업로드하는 코드로 변경하였습니다.
s3 버킷에도 잘 올라오는 것을 확인했습니다!
> fix(route): fix file upload code

- docker-compose.yml
docker-compose.yml의 web에 redis를 추가하였습니다!
> fix(docker): add redis to web

- src/running-route/running-route.service.ts
base64 string으로 넘어오는 이미지 데이터의 확장자를 추가하여 s3에 업로드하였습니다.
png 이미지를 업로드합니다.
s3 버킷에 정상적으로 업로드되며 확장자도 제대로 나오는 것을 확인할 수 있습니다.
> fix(route): add image extension

- src/running-route/running-route.service.ts
프론트 route api 우선 연결을 위해 get mainRoute API의 user data를 주석처리하였습니다.
> fix(route): delete user data from get-main-route API return value

- src/user/dto/create-user.dto.ts
- src/user/entities/user.entity.ts
디자인에 맞추어 birthdate를 생년월일에서 연도만 사용하도록 변경하였습니다.
> feat(user): change birthdate's format from date to number
